services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  frontend:
    restart: on-failure
    build:
      context: ./frontend
    ports:
      - 3001:3000
    depends_on:
      - api
